### ISSUE TITLE
Discussion: Name constructor procs newFoo instead of Foo

### ISSUE THREAD

**Issue by moigagoo** [andreaferretti/patty#12]
As far as I know, in Nim it's considered good coding to name a generator proc for the type ``Foo`` ``newFoo``. In Patty, however, constructors are called the same as the types they construct.

**Comment by andreaferretti** [comment]
actually, not exactly: for instance in the example the type is `Shape`, but the constructors are `Circle` and `Rectangle`.

As far as I can tell, the `newFoo` convention arises to avoid a name clash between the type and the proc itself. In this case, there is no such clash, I and find the result much more readable this way (especially when nesting these constructors)

**Comment by moigagoo** [comment]
Yes, you are right, I overlooked that there's really no clash here. However, I think it has already become an idiom in Nim to call constructors newFoo, so I, as a user of Patty, would expect that newCircle creates a Circle.

Of course, the final decision is all yours, and Patty is already good as it is. But maybe having both Circle and newCircle would be a viable option? If you're good with that, I'll submit a PR.

**Comment by andreaferretti** [comment]
I dunno, they would also be different from what you use in pattern matching. I am not sure I like this asymmetry...

**Comment by moigagoo** [comment]
Probably you are right. Closing the issue.
