### ISSUE TITLE
Add {.used.} Pragma to Procs Made in Variant Macro to Avoid [XDeclaredButNotUsed] Warning

### ISSUE THREAD

**Issue by loloiccl** [andreaferretti/patty#21]
When we define a variant privately as follows

```nim
import patty

variant BTree:
  Nil
  Node(l: ref BTree, r: ref BTree)
```

we get some warning as follows

```
../../.nimble/pkgs/patty-0.3.3/patty.nim(222, 63) Hint: 'patty_btree.==(a: BTree, b: BTree)[declared in ../../.nimble/pkgs/patty-0.3.3/patty.nim(222, 62)]' is declared but not used [XDeclaredButNotUsed]
patty_btree.nim(5, 3) Hint: 'patty_btree.Node(l: ref BTree, r: ref BTree)[declared in patty_btree.nim(5, 2)]' is declared but not used [XDeclaredButNotUsed]
patty_btree.nim(4, 3) Hint: 'patty_btree.Nil()[declared in patty_btree.nim(4, 2)]' is declared but not used [XDeclaredButNotUsed]
```

I want to avoid it by modifying variant macro to use {.used.} pragma.

**Comment by andreaferretti** [comment]
Good suggestion, I will see what I can do (but if in the meantime, you send a PR to add the pragma, it will be faster :-) )

**Comment by loloiccl** [comment]
``newProc`` in module ``macros``
(https://github.com/nim-lang/Nim/blob/master/lib/core/macros.nim#L951)
has no function to use pragma.
So, I will send PR to add this to Nim.

Which do you like to use it after that or to implement another ``newProc`` in patty?

**Comment by andreaferretti** [comment]
If you are not in a hurry, I would wait for the pragma to be accepted in newProc.

Alternatively, one can use newProc as it is to create the proc, and then add the pragma.

**Comment by loloiccl** [comment]
Sorry, ``macros`` has addPragma to use in this case. (https://github.com/nim-lang/Nim/blob/master/lib/core/macros.nim#L1069)
I will modify using this.
