### ISSUE TITLE
Add a helpful error message when added unneeded parens on variant

### ISSUE THREAD

**Issue by NickSeagull** [andreaferretti/patty#28]
First, thank you so much for this project, using it is a bliss! ❤️ 

It would be cool if we errored with something like `Empty parens are not used for a variant with no parameters, please remove them"

Where as, if one writes:

```nim
variant Foo:
  Bar()
```

This errors with:

```text
Error: unhandled exception: 
  ~\.choosenim\toolchains\nim-1.2.6\lib\pure\collections\sequtils.nim(887, 10) `s`gensym3710223.len > 0` 
  Can't fold empty sequences [AssertionError]
```

Perhaps I could try adding this myself and sending a PR? Where should I look?

**Comment by andreaferretti** [comment]
I put an error message. If you want, you can look at the position of the error (it is in the proc `eqFor`) and figure out how to fix the node to make the variant with parens work as well. It should be a matter of detecting a node of kind `nkCall` with a single `nkIdent` as a child, and then replace that node with its only child before the line that does the dispatch

**Comment by NickSeagull** [comment]
Awesome, thanks a lot!
