### ISSUE TITLE
`variant` and `variantp` fail for documentation comments

### ISSUE THREAD

**Issue by dfannius** [andreaferretti/patty#5]
Source file:
```
import patty

variant TestPatty:
  ## If there is only one hash mark instead of two, this compiles fine
  varianta
  variantb
```
Result when attempting to compile:
```
pattyfail.nim(3, 9) template/generic instantiation from here
~/.nimble/pkgs/patty-0.1.7/patty.nim(171) variant(69) defineTypes(25) enumsIn(25, 12) Error: Invalid ADT case: 
```
I tried to fix this myself by filtering out `nnkCommentStmt` nodes in the relevant patty code, but the compiler crashed and I'm not fluent enough in Nim to debug it from there.

Obviously this is not a major issue, especially since patty wouldn't do anything with those documentation comments anyway, but it seems worth fixing.

**Comment by andreaferretti** [comment]
Thank you! I do not have much time right now, but I hope to fix it as soon as possible

**Comment by dfannius** [comment]
Thanks!
